### ISSUE TITLE
Problems connecting reactivesearch to local docker container

### ISSUE THREAD

**Issue by FilipeCunhaRideways** [appbaseio/reactivesearch#453]
I'm trying to connect to my elasticsearch docker container, but I'm getting this error.

![image](https://user-images.githubusercontent.com/31856117/42943126-db056a68-8b59-11e8-907c-24d693b42096.png)

this is my docker container configuration  

![image](https://user-images.githubusercontent.com/31856117/42943183-f45ff03c-8b59-11e8-9c21-de56d92d41bd.png)

and this is my react componet 

![image](https://user-images.githubusercontent.com/31856117/42943285-355267f0-8b5a-11e8-9ae9-b1f6780e09c5.png)

I was able to add items to the index via rest api, this is the structure 

![image](https://user-images.githubusercontent.com/31856117/42943467-bec002b8-8b5a-11e8-861f-f75add144eb9.png)

this is my search request:

![image](https://user-images.githubusercontent.com/31856117/42943551-fa583b92-8b5a-11e8-9c6e-36b9e86d2be6.png)

What is the problem with my configuration?

**Comment by MikkoLuhtasaari** [comment]
I was having similar issues. My temporary fix was to enable CORS from everywhere when developing with these environment variables.
```
      - http.cors.enabled=true
      - http.cors.allow-origin=*
```

When nearing production I'm switch to some sort of middleware to proxy the traffic. With some quick Googling I found this [page](https://github.com/appbaseio-apps/reactivesearch-proxy-server) . Hope it helps.

**Comment by FilipeCunhaRideways** [comment]
this is my new configuration 

```
version: '2'
services:
   elasticsearch:
     image: elasticsearch
     environment:
       - http.cors.enabled=true
       - http.cors.allow-credentials:true
       - http.cors.allow-origin=*
       - http.cors.allow-headers:X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept
     ports:
       - 9200:9200
       - 9300:9300 
```

I also tried removing `- http.cors.allow-credentials:true` but didn't work either
